version: '3.8'

services:
  mysql:
    container_name: gestao_vagas_mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mateusdb
      - MYSQL_DATABASE=gestao_vagas
    command: --default-authentication-plugin=mysql_native_password
